using System.CodeDom.Compiler;
using CoreMachine.UnionLike.Extensions;
using CoreMachine.UnionLike.Model;
using Microsoft.CodeAnalysis;

// ReSharper disable ArgumentsStyleLiteral

namespace CoreMachine.UnionLike.Composers;

public static class AritySourceComposer
{
	public static void BuildArity(SourceProductionContext context, Union union)
	{
		using var output = new StringWriter();
		using var writer = new IndentedTextWriter(output, "\t");

		writer.WriteLine("// <auto-generated/>");
		writer.WriteLine("#nullable enable");
		writer.WriteLine("using System;");
		writer.WriteLine("using System.Threading.Tasks;");
		writer.WriteLine();
		writer.WriteLine("namespace CoreMachine.UnionLike;");
		writer.WriteLine();


		writer.WriteLine($"public abstract record {union.Declaration}");
		writer.Indent++;
		writer.WriteLine(union.WhereClauses);
		writer.Indent--;

		writer.WriteLine('{');
		writer.Indent++;

	#region Match

		// Match
		writer.WriteLine(
			$"public TOut Match<TOut>({union.ArityMembers.JoinSelect(m => $"{m.FuncDeclaration} {m.FuncName}")}) =>"
		);

		writer.WriteSwitchExpression(union.ArityMembers, isMatch: true);

		// MatchAsync
		writer.WriteLine(
			$"public Task<TOut> MatchAsync<TOut>({union.ArityMembers.JoinSelect(m => $"{m.AsyncFuncDeclaration} {m.FuncName}")
			}) =>"
		);

		writer.WriteSwitchExpression(union.ArityMembers, isMatch: true);

		// MatchAsyncValue
		writer.WriteLine(
			$"public ValueTask<TOut> MatchAsyncValue<TOut>({
				union.ArityMembers.JoinSelect(m => $"{m.AsyncValueFuncDeclaration} {m.FuncName}")}) =>"
		);

		writer.WriteSwitchExpression(union.ArityMembers, isMatch: true);

	#endregion

	#region Switch

		// Switch
		writer.WriteLine($"public void Switch({union.ArityMembers.JoinSelect(m => $"{m.ActDeclaration} {m.ActName}")})");
		writer.WriteLine('{');
		writer.Indent++;
		writer.WriteLine("switch (this)");
		writer.WriteLine('{');
		writer.Indent++;
		foreach (var member in union.ArityMembers)
			writer.WriteLine($"case {member.Name} {member.VariableName}: {member.ActName}({member.VariableName}); break;");

		writer.Indent--;
		writer.WriteLine('}');
		writer.Indent--;
		writer.WriteLine('}');
		writer.WriteLine();

		// SwitchAsync
		writer.WriteLine(
			$"public Task SwitchAsync({union.ArityMembers.JoinSelect(m => $"{m.AsyncActDeclaration} {m.ActName}")}) =>"
		);

		writer.WriteSwitchExpression(union.ArityMembers, isMatch: false);

		// SwitchAsyncValue
		writer.WriteLine(
			$"public ValueTask SwitchAsyncValue({
				union.ArityMembers.JoinSelect(m => $"{m.AsyncValueActDeclaration} {m.ActName}")}) =>"
		);

		writer.WriteSwitchExpression(union.ArityMembers, isMatch: false);

	#endregion


		writer.Indent--;
		writer.WriteLine('}');

		writer.WriteLine();

		string generatedFileName = $"Union.T{union.Arity}.g." + $"cs";
		context.AddSource(generatedFileName, output.ToString());
	}

	private static void WriteSwitchExpression(this IndentedTextWriter writer, ArityMember[] arityMembers, bool isMatch)
	{
		writer.Indent++;
		writer.WriteLine("this switch");
		writer.WriteLine('{');
		writer.Indent++;

		foreach (var member in arityMembers)
			writer.WriteLine(
				isMatch
					? $"{member.Name} {member.VariableName} => {member.FuncName}({member.VariableName}),"
					: $"{member.Name} {member.VariableName} => {member.ActName}({member.VariableName}),"
			);

		writer.WriteLine("_ => throw new InvalidOperationException()");
		writer.Indent--;
		writer.WriteLine("};");
		writer.Indent--;
		writer.WriteLine();
	}
}
