//HintName: CoreMachine.UnionLike.Attributes.UnionAttribute.g.cs
// <auto-generated/>

#nullable enable

namespace CoreMachine.UnionLike.Attributes;

[global::System.CodeDom.Compiler.GeneratedCodeAttribute("CoreMachine.UnionLike", "1.0.0")]
[global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
public class UnionAttribute : global::System.Attribute { }
