namespace CoreMachine.UnionLike;

public class GenerationCore
{
    private static readonly string GeneratedCodeAttribute =
        $"""[global::System.CodeDom.Compiler.GeneratedCodeAttribute("{typeof(GenerationCore).Namespace}", "1.0.0")]""";

    public static readonly string NameSpace = "Roslyn.Generated";

    public static readonly string AttributeName = nameof(UnionAttribute);
    
    public static string FullyQualifiedAttributeName => NameSpace + '.' + AttributeName; 
    
    public static readonly string UnionAttribute =
        $$"""
          // <auto-generated/>
          #nullable enable

          namespace {{NameSpace}};
          {{GeneratedCodeAttribute}}
          [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
          public class UnionAttribute : global::System.Attribute
          {
          }

          """;

    
}