using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace CoreMachine.UnionLike.Core;

public static class AttributeCore
{
	public static readonly string AttributeNamespace = "CoreMachine.UnionLike.Attributes";
	public static readonly string FullyQualifiedAttributeName = AttributeNamespace + '.' + nameof(UnionAttribute);

	public static readonly string GeneratedCodeAttribute =
		$"""[global::System.CodeDom.Compiler.GeneratedCodeAttribute("{typeof(UnionGenerator).Namespace}", "1.0.0")]""";


	public static readonly string UnionAttribute =
		$$"""
		  // <auto-generated/>
		  #nullable enable

		  namespace {{AttributeNamespace}};
		  {{GeneratedCodeAttribute}}
		  [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
		  public class UnionAttribute : global::System.Attribute
		  {
		  }

		  """;

	public static void GenerateMarkerAttribute(IncrementalGeneratorPostInitializationContext context)
	{
		context.AddSource($"{FullyQualifiedAttributeName}.g.cs",
			SourceText.From(UnionAttribute, Encoding.UTF8));
	}
}
